#!/usr/bin/python
# -*- coding:utf-8 -*-
# oss配置

OSS_ACCESS_KEY_ID = 'YOUR ALIYUN OSS ACCESS KEY ID'
OSS_ACCESS_KEY_SECRET = 'YOUR ALIYUN OSS ACCESS KEY SECRET'
OSS_END_POINT = 'YOUR ALIYUN OSS BUCKET ENDPOINT'

OSS_BUCKETNAME = []
OSS_DOMAIN = {'BUCKETNAME': 'YOUR BUCKET ACCESS DOMAIN', }
